"""Regenerate the markdown tables in guides/enterprise-rag/ from data/scored.json.

Keeps the published tables derivable from the dataset rather than hand-written,
so a change to WEIGHTS in clone_score.py flows through to the guide.
"""

import json
import os
from collections import defaultdict

HERE = os.path.dirname(os.path.abspath(__file__))
SCORED = os.path.join(HERE, "..", "data", "scored.json")
GUIDE = os.path.join(HERE, "..", "guides", "enterprise-rag")

KIND_ORDER = ["reference_architecture", "platform", "library", "application",
              "deployable_sample", "eval_harness", "tutorial"]


def density(r, signal, key):
    return r["evidence"][signal]["per_100_rag_files"].get(key, 0)


def main():
    with open(SCORED) as f:
        all_rows = json.load(f)
    rows = [r for r in all_rows if not r.get("excluded") and r.get("signals")]
    excluded = [r for r in all_rows if r.get("excluded")]

    by_kind = defaultdict(list)
    for r in rows:
        by_kind[r.get("kind", "unclassified")].append(r)

    out = [
        "# Repository evaluations",
        "",
        "Generated by `tools/gen_tables.py` from `data/scored.json`. Do not edit by hand.",
        "",
        f"{len(rows)} repositories scored; {len(excluded)} excluded for having no "
        "retrieval surface (see methodology).",
        "",
        "Scores are comparable **within** a kind, not across kinds. Star count is not "
        "an input to any column.",
        "",
        "`Ops` operational burden · `Eval` retrieval evaluation · `Ent` enterprise gate · "
        "`Bus` bus factor · `ACL` document-ACL density per 100 RAG files · "
        "`RetrM` retrieval-metric density.",
    ]

    for kind in KIND_ORDER + sorted(set(by_kind) - set(KIND_ORDER)):
        group = sorted(by_kind.get(kind, []), key=lambda r: -r["composite"])
        if not group:
            continue
        out += ["", f"## {kind.replace('_', ' ')} ({len(group)})", "",
                "| Repo | Score | Ops | Eval | Ent | Bus | ACL | RetrM |",
                "|---|---|---|---|---|---|---|---|"]
        for r in group:
            s = r["signals"]
            out.append(
                f"| [{r['full_name']}]({r['html_url']}) | {r['composite']:.3f} "
                f"| {s['operational']:.2f} | {s['evaluation']:.2f} | {s['enterprise']:.2f} "
                f"| {s['bus_factor']:.2f} | {density(r, 'enterprise', 'doc_acl'):.1f} "
                f"| {density(r, 'evaluation', 'retrieval_metrics'):.1f} |")

    if excluded:
        out += ["", "## Excluded: no retrieval surface", "",
                "Fewer than three files touching retrieval. Excluded rather than scored "
                "zero, so they do not sit in the dataset looking like weak RAG projects.",
                ""]
        out += [f"- `{r['full_name']}`" for r in sorted(excluded, key=lambda r: r["full_name"])]

    os.makedirs(GUIDE, exist_ok=True)
    path = os.path.join(GUIDE, "repo-evaluations.md")
    with open(path, "w") as f:
        f.write("\n".join(out) + "\n")

    # Headline figures quoted in README.md, recomputed so they cannot drift.
    acl = [r for r in rows if density(r, "enterprise", "doc_acl") > 0]
    met = [r for r in rows if density(r, "evaluation", "retrieval_metrics") > 0]
    rei = [r for r in rows if density(r, "operational", "reindex_path") > 0]
    both = [r for r in acl if density(r, "evaluation", "retrieval_metrics") > 0]
    print(f"wrote {path} ({len(rows)} repos)")
    print(f"  doc ACL              {len(acl)}/{len(rows)} ({100*len(acl)//len(rows)}%)")
    print(f"  retrieval metrics    {len(met)}/{len(rows)} ({100*len(met)//len(rows)}%)")
    print(f"  reindex path         {len(rei)}/{len(rows)} ({100*len(rei)//len(rows)}%)")
    print(f"  both ACL + metrics   {len(both)}/{len(rows)}")


if __name__ == "__main__":
    main()
